### ISSUE TITLE
Can i use you port with the Signalr PCL package?

### ISSUE THREAD

**Issue by vinguan** [NVentimiglia/WebSocket.Portable#1]

**Comment by NVentimiglia** [comment]
Can you explain and link ?

**Comment by vinguan** [comment]
The current https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Client/ does not support web sockets with Xamarin, because System.Net.WebSockets is not available in none of the PCL profiles. Im asking if i can use you port of WebSockets with Signalr?

**Comment by NVentimiglia** [comment]
I could, but do not plan to. I have too much on my plate as it is right now. 

You can try to make the port yourself. If you have any questions feel free to ask.

**Comment by NVentimiglia** [comment]
That said, it might be easier to instead use the Android / iOS SignalR SDKs and write a bridge application to connect the two. That way you can bypass the difficulties (and shortcomings) of mono networking.
