### ISSUE TITLE
Handshake failed

### ISSUE THREAD

**Issue by kabsila** [NVentimiglia/WebSocket.Portable#3]
I use this package in Xamarin.form to connect to websocket server. and i got exception
"Handshake failed: Invalid status sode." but it connect to ws://echo.websocket.org correctly. 
and when i use websocket4net package it connect to my  websocket server correctly but it not pcl. 
My websocket server use http://tornado.readthedocs.org/en/latest/websocket.html with port 8888 like this
ws://xx.xx.xx.xx:8888/ws

Can you fix it or tell me what happened? 
Thank you for awesome package.

**Comment by NVentimiglia** [comment]
Could you post some code ? 

Try looking here to see if your code matches.

https://github.com/NVentimiglia/WebSocket.Portable/blob/master/Examples/Websockets.XamExample/Websockets.XamExample/Websockets.XamExample/Page1.cs

**Comment by kabsila** [comment]
My code 

         async void OnConnectClicked(object sender, EventArgs args)
		{
			var client = new WebSocketClient();
			client.Opened += websocket_Opened;
			client.Closed += websocket_Closed;
			client.MessageReceived += websocket_MessageReceived;

			//Never Ending
			await client.OpenAsync(webSocketUrl.Text);
			Debug.WriteLine("TestWebsocketPortable");
		}


		private void websocket_MessageReceived(IWebSocketMessage obj)
		{
			Debug.WriteLine(obj.ToString());

		}

		private void websocket_Closed()
		{
			Debug.WriteLine("websocket_Closed");

		}

		private void websocket_Opened()
		{
			Debug.WriteLine("websocket_Opened");

		}

**Comment by NVentimiglia** [comment]
> //Never Ending

I ran into two very similar issues.


1) The TcpConnection ReadLine method was not parsing the string correctly. I was originally using the standard ReadLine method included in the stream reader. I ended up writing my own replacement to solve the issue.

https://github.com/NVentimiglia/WebSocket.Portable/blob/master/WebSocket.Portable/WebSocket.Portable/_Implementation/TcpConnection.cs#L76

Try adding a breakpoint to see if that has resurfaced.



2) the Windows platform the issue was deeper down in rda.Sockets (the first test in the above linked testclass demonstrated this). This was resolved by a recent update.

**Comment by kabsila** [comment]
Now, I already know what the problem is parsing the string not correctly.
Hope you will fix this issues and update package soon.
Thank you.

**Comment by NVentimiglia** [comment]
I`m confused ? Do you have a fix for your server ? I cant really push an update if It is working fine on my servers.

**Comment by kabsila** [comment]
Sorry for confusion
I just think OpenAsync method is not support following uri format ->  ws://xx.xx.xx.xx:yyyy/zz

sorry if my english make you confused.

**Comment by kabsila** [comment]
finally, I change my websocket server port to 80 and remove path /zz.
now I can connected to my websocket server correctly.

**Comment by NVentimiglia** [comment]
Great.

**Comment by deus42** [comment]
I ran into the same problem! Hopefully I was able to find out a problem with your realization.
In WebSocketBase class in method ConnectAsync you explicitly define ports 80 and 443 for ws and wss respectively. but within our poject we run webSockets on port 8010 - and this cannot be changed, and I cannot use this method in right way.
I see possible 2 solutions: 1. overload method can be created with additional port parameter and 2. you can parse server:port from uri appropriately using regex.
In addition I can fork and fix it if you don't have a time.

King regards,
Alexey

**Comment by NVentimiglia** [comment]
Try out 1.2.4. It now supports custom ports and manual toggling of SSL.

var client = new WebSocketClient();
await client.OpenAsync("ws://echo.websocket.org"m 80, false);

**Comment by deus42** [comment]
Thank you. It works now. You may close the ticket.

-Alexey
