### ISSUE TITLE
Unable to set the subprotocol on connection

### ISSUE THREAD

**Issue by jonclare** [NVentimiglia/WebSocket.Portable#4]
The `WebSocketResponseHandshake` class provides the ability to set the subprotocol, but a default handshake is created during the `WebSocketClientBase.OpenAsync` method and as far as I can tell it's not possible to set the subprotocol when opening the connection.

This is needed to connect to certain servers.

**Comment by NVentimiglia** [comment]
Thanks for the commit !

**Comment by jonclare** [comment]
No worries.
I've been doing some work recently on getting [WampSharp](https://github.com/Code-Sharp/WampSharp) working with a PCL websocket library, and this change was needed.

If you're able to do a release at some point with the sub protocol changes that would greatly assist me as I don't want to put the stuff from my fork onto NuGet and create a potentially confusing alternative to your library!
